name: Deploy FastAPI AI Service to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/ai_service"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/ai_service
            
            # 필요한 패키지 설치
            sudo apt update
            sudo apt install -y python3-full python3-pip python3-venv
            
            # 기존 venv 제거 및 새로 생성
            rm -rf venv
            python3 -m venv venv
            
            # 가상환경 활성화 및 패키지 설치
            source venv/bin/activate
            pip install -r requirements.txt
            
            # 기존 프로세스 종료
            sudo fuser -k -n tcp 8000 || true
            
            # 서버 재시작 (프록시 헤더와 HTTPS 지원 추가)
            nohup venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*" > ./output.log 2>&1 &